### ISSUE TITLE
Not working anymore. I think it has something to do with how Skillshare changed the layout of the website.

### ISSUE THREAD

**Issue by Asgerspange** [calvinhobbes23/Skillshare-DL#14]
Traceback (most recent call last):
File "/root/.Skillshare-DL/dl.py", line 16, in
main()
File "/root/.Skillshare-DL/dl.py", line 11, in main
dl.download_course_by_url(course_url)
File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
self.download_course_by_class_id(m.group(1))
File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by mendelsphotography** [comment]
same here

**Comment by kristinkoe** [comment]
same, they dont allow you to view the full course page without a membership, so the downloader cant parse every video in the course, only the intro which is unlocked. they also made the redirect to the member signup page stronger i think, before i could bypass it by editing the link and blocking redirects. now that doesn't stop it
