### ISSUE TITLE
Download a copy of Skillshare-DL that works with Python 3+ here!

### ISSUE THREAD

**Issue by StupidRepo** [calvinhobbes23/Skillshare-DL#23]
I cloned the repo using `git` but when I run `python3 dl.py "[link]"`, it returns this:

```
$ python3 dl.py "[link]"
Traceback (most recent call last):
  File "/Users/[me]/Desktop/SkillshareDL/dl.py", line 3, in <module>
    from magic import cookie
ImportError: bad magic number in 'magic': b'B\r\r\n'
```

**Comment by StupidRepo** [comment]
All fixed! Just extracted the cookie (use [decompiler.com](https://www.decompiler.com) for extraction) then removed the `from magic import cookie` and added the cookie as a variable `cookie = "[cookie]"`.

**Comment by StupidRepo** [comment]
[SkillshareDL.zip](https://github.com/calvinhobbes23/Skillshare-DL/files/8541772/SkillshareDL.zip)

**Comment by lakhanadewar** [comment]
Thank you it working
usage 
open cmd
type python dl.py "your_course_ Url"

**Comment by data2005** [comment]
Hi,

Thank you but when using I get the following error. Please anyone help?

Traceback (most recent call last):
  File "C:\shared\x\SkillshareDL\SkillshareDL\dl.py", line 17, in <module>
    main()
  File "C:\shared\x\SkillshareDL\SkillshareDL\dl.py", line 12, in main
    dl.download_course_by_url(course_url)
  File "C:\shared\x\SkillshareDL\SkillshareDL\skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "C:\shared\x\SkillshareDL\SkillshareDL\skillshare.py", line 58, in download_course_by_class_id
    slugify(teacher_name),
  File "C:\Users\barla\AppData\Local\Programs\Python\Python39\lib\site-packages\slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined

**Comment by Gimbotries** [comment]
Please add a simple text file in the folder over how to use it. Do I have to download github or a simple python running software would work, If it could work with cmd prompt then How to do it what to type and all. Please HELP.
