### ISSUE TITLE
New Bug!!!

### ISSUE THREAD

**Issue by seeker24** [calvinhobbes23/Skillshare-DL#25]
I just report this bug and I hope to be rectified soon.
Thanks

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 2, in <module>
    from skillshare import Skillshare, splash
  File "/root/.Skillshare-DL/skillshare.py", line 2, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

this issue at the beginning of download

**Comment by Seanobucko** [comment]
Any progress with this :( having it too

**Comment by mendelsphotography** [comment]
same

**Comment by lakhanadewar** [comment]
run this before using it
`pip install cloudscraper`

**Comment by mendelsphotography** [comment]
> use this in windows [skillsharedl](https://github.com/calvinhobbes23/Skillshare-DL/issues/23)

thanks will try
