### ISSUE TITLE
only the first video downloading then followed by an error

### ISSUE THREAD

**Issue by BradTheBlue** [calvinhobbes23/Skillshare-DL#28]
the error:
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

appears after downloading the first video.

**Comment by CrissGill** [comment]
Same issue

**Comment by CrissGill** [comment]
> the error:
> Traceback (most recent call last):
>   File "/root/.Skillshare-DL/dl.py", line 16, in <module>
>     main()
>   File "/root/.Skillshare-DL/dl.py", line 11, in main
>     dl.download_course_by_url(course_url)
>   File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
>     self.download_course_by_class_id(m.group(1))
>   File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
>     raise Exception('Failed to read video ID from data')
> Exception: Failed to read video ID from data
> 
> appears after downloading the first video.

Struggling with same issue...

**Comment by overhaul666** [comment]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data


I am getting same issue

**Comment by vampireprincess** [comment]
same issue here

**Comment by johnktrz** [comment]
it's dead

**Comment by MolangPiupiu** [comment]
I have the same issue

**Comment by overhaul666** [comment]
Is there any other way to get skill share course (ofc for free)

**Comment by johnktrz** [comment]
> Is there any other way to get skill share course

There is, but this is the easiest code to use for non-programmer

Save us @calvinhobbes23 :)

**Comment by CrissGill** [comment]
> > Is there any other way to get skill share course
> 
> There is, but this is the easiest code to use for non-programmer
> 
> Save us @calvinhobbes23 :)

Ok , so if you know any other way please share that skill ;)

**Comment by scaruslooner** [comment]
Same issue

**Comment by data2005** [comment]
I am not much familiar with python language but a quick look at the code it seems that the Skillshare account info that was used to download videos is perhaps no longer valid as all videos except first one has  no video hash value which is exposed only if one has a valid subscription. Thanks

**Comment by calvinhobbes23** [comment]
This is account issue. If someone has an account to spare, I can fix it. please upload credentials in a text file here:
https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5
password: share

file will vanish. This is by design.
Thanks

**Comment by isurajcdry** [comment]
> This is account issue. If someone has an account to spare, I can fix it. please upload credentials in a text file here: https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5 password: share
> 
> file will vanish. This is by design. Thanks

You mean a GitHub account?

**Comment by calvinhobbes23** [comment]
skillshare account is needed for this to be fixed. I will fix the repo code once I have the account

**Comment by Myselfmru** [comment]
> skillshare account is needed for this to be fixed. I will fix the repo code once I have the account

Can this be a free skillshare account?  I mean there are 30 days trials.... Can we contribute in sharing an account for that?

**Comment by overhaul666** [comment]
> > skillshare account is needed for this to be fixed. I will fix the repo code once I have the account
> 
> Can this be a free skillshare account? I mean there are 30 days trials.... Can we contribute in sharing an account for that?

ig it will work, if you can access the complete course...

**Comment by AbdulUsman45** [comment]
I have the skillshare account !!

**Comment by isurajcdry** [comment]
@AbdulUsman45, kindly upload the ID and password in a text file to https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5 

Password: share

@calvinhobbes23 will work on the code accordingly. 

Thank you so much!

**Comment by AbdulUsman45** [comment]
### Guys, it's working need to make some changes in the code  !!!
![image](https://user-images.githubusercontent.com/92779783/182337798-1922b963-3834-4460-9d02-79b5b16bdbc2.png)

### Follow this steps to download the Video or course for free 

Note: `For Windows Users`

## 1. Open Command Prompt or `Windows` +  `R` 

- And  Type The following code 
-  ```git clone https://github.com/calvinhobbes23/Skillshare-DL.git```
![image](https://user-images.githubusercontent.com/92779783/182344152-ca6b8ee9-953d-4f28-b14a-513b3c67327c.png)
-  Make sure to change the dl.py file 
- You can find the file in the Default location 
```C:\Users\YOUR_USERPROFILE \Skillshare-DL```

![image](https://user-images.githubusercontent.com/92779783/182348421-6ef6bfbc-155b-49a2-ba5c-c0239ef5bed6.png)


> Replace the ```dl.py``` code with the following code.
```import sys, os
from skillshare import Skillshare, splash


# or by class ID:
# dl.download_course_by_class_id(189505397)

def main():
    dl = Skillshare("PHPSESSID=If You want this code txt Me")
    course_url = sys.argv[1]
    dl.download_course_by_url(course_url)


if __name__ == "__main__":
    splash()
    main()
``` 
Note: `If You want PHPSESSID Text Me` or `Mail Me - abdulu767@gmail.com`

- After You have done all the changes 
- Type the command in the terminal (Inorder to change the directory ) ```cd Skillshare-DL```
- Next Type ```pip install -r requriments.txt```

![image](https://user-images.githubusercontent.com/92779783/182351017-bcfddeaf-e6aa-4d1a-8d73-e57878f7ca5a.png)
- After you have successfully installed all required packages 
- Type ```python dl.py "COURSE_LINK" ```
- Now, All the files will be saved one by one

**Comment by data2005** [comment]
Thank you for your help and time. But I could not get it to work... please see below. Please anyone help?


Traceback (most recent call last):
  File "dl.py", line 19, in <module>
    main()
  File "dl.py", line 14, in main
    dl.download_course_by_url(course_url)
  File "/home/osboxes/sk/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/home/osboxes/sk/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by CrissGill** [comment]
> Thank you for your help and time. But I could not get it to work... please see below. Please anyone help?
> 
> 
> Traceback (most recent call last):
>   File "dl.py", line 19, in <module>
>     main()
>   File "dl.py", line 14, in main
>     dl.download_course_by_url(course_url)
>   File "/home/osboxes/sk/skillshare.py", line 32, in download_course_by_url
>     self.download_course_by_class_id(m.group(1))
>   File "/home/osboxes/sk/skillshare.py", line 72, in download_course_by_class_id
>     raise Exception('Failed to read video ID from data')
> Exception: Failed to read video ID from data
> 

Did you got PHPSESSID❓

**Comment by data2005** [comment]
No Thanks I did not....how do I do that?  Thank you

**Comment by CrissGill** [comment]
> No Thanks I did not....how do I do that?  Thank you

We need a working skill share account if you have, then send it to @calvinhobbes23 that would help all of us 
Thank you

**Comment by data2005** [comment]
I see it is the same account issue as I had found out. Sorry I do not have working skillshare account. I have emailed as outlined in the comments by [AbdulUsman45] . Let's see what happens...if I get it, I can maybe able to tell what to do.

**Comment by AbdulUsman45** [comment]
> > Thank you for your help and time. But I could not get it to work... please see below. Please anyone help?
> > Traceback (most recent call last):
> > File "dl.py", line 19, in 
> > main()
> > File "dl.py", line 14, in main
> > dl.download_course_by_url(course_url)
> > File "/home/osboxes/sk/skillshare.py", line 32, in download_course_by_url
> > self.download_course_by_class_id(m.group(1))
> > File "/home/osboxes/sk/skillshare.py", line 72, in download_course_by_class_id
> > raise Exception('Failed to read video ID from data')
> > Exception: Failed to read video ID from data
> 
> Did you got PHPSESSID❓

Send me the video link to My mail abdulu767@gmail.com

**Comment by AbdulUsman45** [comment]
> I see it is the same account issue as I had found out. Sorry I do not have working skillshare account. I have emailed as outlined in the comments by [AbdulUsman45] . Let's see what happens...if I get it, I can maybe able to tell what to do.

I have Send You @data2005

**Comment by AbdulUsman45** [comment]
Join My Telegram channel https://t.me/+TD1ZMA0oHGY3ZTM1

**Comment by data2005** [comment]
Sorry do not have telegram account.... Thanks

**Comment by AbdulUsman45** [comment]
> Sorry do not have a telegram account.... Thanks

@data2005 It's ok I will mail you

**Comment by data2005** [comment]
Thanks. I eagerly look forward to it.

**Comment by johnktrz** [comment]
> No Thanks I did not....how do I do that? Thank you

You can get PHPSESSID using a Cookie manager in chrome extension

**Comment by AbdulUsman45** [comment]
Join my telegram (https://t.me/+TD1ZMA0oHGY3ZTM1)
I will send you the course or video fast as possible !!!

**Comment by aditya-pushkar** [comment]
@AbdulUsman45  Can you help me to get course ?

**Comment by isurajcdry** [comment]
@AbdulUsman45 and @calvinhobbes23 guys is there a way to make the Skillshare DL code work?

**Comment by calvinhobbes23** [comment]
I am still waiting for someone to share a skillshare account. I don't have a way to get one, sorry.

**Comment by overhaul666** [comment]
@AbdulUsman45 come on bro share ur skillshare acc. and stop promoting ur telegram 

> I am still waiting for someone to share a skillshare account. I don't have a way to get one, sorry.

**Comment by Myselfmru** [comment]
Guys, from what I read on the threads, a free Skillshare account will work. Given that there are 30 days trials, if 12 members share a trial account every month, we can make this work for a year. Just an example. Now correct me if I'm wrong. So I don't see what could go wrong. OR am I on the wrong track? Please guide.

**Comment by CrissGill** [comment]
> Guys, from what I read on the threads, a free Skillshare account will work. Given that there are 30 days trials, if 12 members share a trial account every month in turn, we can make this work for a year. Just an example. Now correct me if I'm wrong. So I don't see what could go wrong. OR am I on the wrong track? Please guide. 

How to get 30 days free trial❓

**Comment by data2005** [comment]
if you go to https://www.skillshare.com/ site at the top is currently 1 month trial offer. such as link https://www.skillshare.com/membership/checkout?via=teacher-referral-blue-banner . You will have to register and add payment details. You will not be charged till 30th day (maybe cancel on the 29th day).

**Comment by CrissGill** [comment]
> if you go to https://www.skillshare.com/ site at the top is currently 1 month trial offer. such as link https://www.skillshare.com/membership/checkout?via=teacher-referral-blue-banner . You will have to register and add payment details. You will not be charged till 30th day (maybe cancel on the 29th day). 

![Screenshot_2022-08-07-21-08-17-67_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/102593716/183298926-0815e590-8814-406b-8631-1214929a1518.jpg)
i think it depends upon the nation to nation.... I can't see any 30 days trial

**Comment by data2005** [comment]
Maybe try with VPN? I tried and I could see the following

Get 1 free month of Skillshare
    Get unlimited access to thousands of inspiring classes
    Taught by industry leaders & working professionals
    Topics include illustration, design, photography, and more

**Comment by calvinhobbes23** [comment]
Hang-on please. I created an account will work on it tonight.

**Comment by data2005** [comment]
Great, many thanks to calvinhobbes23

**Comment by ghost** [comment]
> This is account issue. If someone has an account to spare, I can fix it. please upload credentials in a text file here: https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5 password: share
> 
> file will vanish. This is by design. Thanks

you can take my account. it has like 1.5 months of sub.

**Comment by ghost** [comment]
> > This is account issue. If someone has an account to spare, I can fix it. please upload credentials in a text file here: https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5 password: share
> > file will vanish. This is by design. Thanks
> 
> you can take my account. it has like 1.5 months of sub.

i sent my account in your shared folder. i know the trick to create 3 months trial account for free. when this account is expired, please let me know. I will give you another account.

**Comment by CrissGill** [comment]
> > > This is account issue. If someone has an account to spare, I can fix it. please upload credentials in a text file here: https://www.saggy.xyz/folders/cb86e97869fad500e678860850cc11a5 password: share
> > > file will vanish. This is by design. Thanks
> > 
> > you can take my account. it has like 1.5 months of sub.
> 
> i sent my account in your shared folder. i know the trick to create 3 months trial account for free. when this account is expired, please let me know. I will give you another account.

Thank you for this and to all the members that involves in skillshare dl to make it working ✌️🤩

**Comment by surajcdry** [comment]
Thank you so much @calvinhobbes23! Till when will this be solved? Really needed a course asap.

**Comment by calvinhobbes23** [comment]
So I have some bad news. As someone earlier explained in another issue comment, the cookie now needs PHPSESSID value for it to work however that expires in 1-2 minutes and download stops. It seems skillshare may be fighting this download method and they seem to be succeeding. I am not the original developer but if someone has a solution please create a pull request and I will merge.

**Comment by calvinhobbes23** [comment]
Thank you @saifeealii  for the account however!
EDIT: fixed the name

**Comment by Jhonny1021** [comment]
@calvinhobbes23 I have been able to download from python directly and in the terminal as the steps that are described

**Comment by data2005** [comment]
Thanks. What are the steps?

**Comment by calvinhobbes23** [comment]
> ### Guys, it's working need to make some changes in the code !!!
> ![image](https://user-images.githubusercontent.com/92779783/182337798-1922b963-3834-4460-9d02-79b5b16bdbc2.png)
> 
> ### Follow this steps to download the Video or course for free
> Note: `For Windows Users`
> 
> ## 1. Open Command Prompt or `Windows` + `R`
> * And  Type The following code
> * `git clone https://github.com/calvinhobbes23/Skillshare-DL.git`
>   ![image](https://user-images.githubusercontent.com/92779783/182344152-ca6b8ee9-953d-4f28-b14a-513b3c67327c.png)
> * Make sure to change the dl.py file
> * You can find the file in the Default location
>   `C:\Users\YOUR_USERPROFILE \Skillshare-DL`
> 
> ![image](https://user-images.githubusercontent.com/92779783/182348421-6ef6bfbc-155b-49a2-ba5c-c0239ef5bed6.png)
> 
> > Replace the `dl.py` code with the following code.
> 
> ```
> import sys, os
> from skillshare import Skillshare, splash
> 
> 
> # or by class ID:
> # dl.download_course_by_class_id(189505397)
> 
> def main():
>     dl = Skillshare("PHPSESSID=If You want this code txt Me")
>     course_url = sys.argv[1]
>     dl.download_course_by_url(course_url)
> 
> 
> if __name__ == "__main__":
>     splash()
>     main()
> ```
> 
> Note: `If You want PHPSESSID Text Me` or `Mail Me - abdulu767@gmail.com`
> 
> * After You have done all the changes
> * Type the command in the terminal (Inorder to change the directory ) `cd Skillshare-DL`
> * Next Type `pip install -r requriments.txt`
> 
> ![image](https://user-images.githubusercontent.com/92779783/182351017-bcfddeaf-e6aa-4d1a-8d73-e57878f7ca5a.png)
> 
> * After you have successfully installed all required packages
> * Type `python dl.py "COURSE_LINK" `
> * Now, All the files will be saved one by one

This method very well works but it means the person downloading the course must have access to the cookie/account in their browser to extract PHPSESSID value and most likely needs to use the same pc to download. i.e. no colab.

**Comment by data2005** [comment]
Thank you. The big issue here is that for downloading the course one needs membership access to skillshare. Once you had taken a free trial  membership, one cannot reapply for a free trail again. Skillshare keeps note of account info (creit card , paypal etc)  and have been known to charge subscription fee right away. They no longer offer monthly subscription so one can be charged yearly subscription's hefty cost!

Unless someone is willing to share skillshare account login deatils?

**Comment by Myselfmru** [comment]
> Thank you. The big issue here is that for downloading the course one needs membership access to skillshare. Once you had taken a free trial membership, one cannot reapply for a free trail again. Skillshare keeps note of account info (creit card , paypal etc) and have been known to charge subscription fee right away. They no longer offer monthly subscription so one can be charged yearly subscription's hefty cost!
> 
> Unless someone is willing to share skillshare account login deatils?

Exactly, as I mentioned earlier, its a collaborative task. Every member interested in this can share their free trial account in turn after the 30 day limit. Depending on the number of participants, we can keep this alive for a certain period. But the critical thing here is that sharing the credentials will also disclose the credit card info which IMHO will make this idea collapse. The good thing is that calvinhobbes23 did a very laudable job to give us the steps required to download the courses for free. It's now on us to deal with the free membership trials and credit cards issue.

**Comment by calvinhobbes23** [comment]
@Myselfmru To be Honest, credit for the new steps go to @AbdulUsman45 I believe.

**Comment by CrissGill** [comment]
> @Myselfmru To be Honest, credit for the new steps go to @AbdulUsman45 I believe.
> 

I need magic.pyc source code to edit

**Comment by MusicCookie** [comment]
> ### Guys, it's working need to make some changes in the code !!!
> ![image](https://user-images.githubusercontent.com/92779783/182337798-1922b963-3834-4460-9d02-79b5b16bdbc2.png)
> 
> ### Follow this steps to download the Video or course for free
> Note: `For Windows Users`
> 
> ## 1. Open Command Prompt or `Windows` + `R`
> * And  Type The following code
> * `git clone https://github.com/calvinhobbes23/Skillshare-DL.git`
>   ![image](https://user-images.githubusercontent.com/92779783/182344152-ca6b8ee9-953d-4f28-b14a-513b3c67327c.png)
> * Make sure to change the dl.py file
> * You can find the file in the Default location
>   `C:\Users\YOUR_USERPROFILE \Skillshare-DL`
> 
> ![image](https://user-images.githubusercontent.com/92779783/182348421-6ef6bfbc-155b-49a2-ba5c-c0239ef5bed6.png)
> 
> > Replace the `dl.py` code with the following code.
> 
> ```
> import sys, os
> from skillshare import Skillshare, splash
> 
> 
> # or by class ID:
> # dl.download_course_by_class_id(189505397)
> 
> def main():
>     dl = Skillshare("PHPSESSID=If You want this code txt Me")
>     course_url = sys.argv[1]
>     dl.download_course_by_url(course_url)
> 
> 
> if __name__ == "__main__":
>     splash()
>     main()
> ```
> 
> Note: `If You want PHPSESSID Text Me` or `Mail Me - abdulu767@gmail.com`
> 
> * After You have done all the changes
> * Type the command in the terminal (Inorder to change the directory ) `cd Skillshare-DL`
> * Next Type `pip install -r requriments.txt`
> 
> ![image](https://user-images.githubusercontent.com/92779783/182351017-bcfddeaf-e6aa-4d1a-8d73-e57878f7ca5a.png)
> 
> * After you have successfully installed all required packages
> * Type `python dl.py "COURSE_LINK" `
> * Now, All the files will be saved one by one

I opened cmd and typed in the first command "git clone https://github.com/calvinhobbes23/Skillshare-DL.git", but I was met with an error... : 
"C:\Users\MY_USERPROFILE>git clone https://github.com/calvinhobbes23/Skillshare-DL.git
'git' is not recognized as an internal or external command,
operable program or batch file."

What should I do ?

P.S I am running on Windows 10

**Comment by calvinhobbes23** [comment]
install git using chocolatey or as mentioned here:
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
if you dont have the account password OR cookie, no point in trying.

**Comment by Seanobucko** [comment]
Can anybody help me im on Mac and for the life of me cannot figure this out

**Comment by tarabrose** [comment]
im on a mac too!  how can i do this?

**Comment by CrissGill** [comment]
> Can anybody help me im on Mac and for the life of me cannot figure this out

You can use Google colab
{Link :- https://colab.research.google.com/drive/1cLcPjRYeMZ0f2uKN6-poCaAies76uWR5?usp=sharing } save your all courses in Google drive then simply use Google take out . Extract your data from Google drive ✌️

**Comment by abdul-usman** [comment]
If you want any course I will download and send just email me - [abdulu767@gmail.com](mailto:abdulu767@gmail.com)
