### ISSUE TITLE
i am not able to download course from skillshare

### ISSUE THREAD

**Issue by suryaprakashsahani** [calvinhobbes23/Skillshare-DL#33]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 72, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by abdul-usman** [comment]
@suryaprakashsahani  Dude, You Can buy SkillShare Acc for $0.59/ Month on this [Website](https://app.toolzbuy.com/aff/go/abdulu46)
