### ISSUE TITLE
Getting Error while downloading the files

### ISSUE THREAD

**Issue by joyhappy2022** [calvinhobbes23/Skillshare-DL#38]
Hey Bro

I'm having error while downloading the video.

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 2, in <module>
    from skillshare import Skillshare, splash
  File "/root/.Skillshare-DL/skillshare.py", line 1, in <module>
    import requests, json, sys, re, os
ModuleNotFoundError: No module named 'requests'

I've followed every steps but after placing course link and then run the code then this will happen. How to resolve this error?

Thanks

**Comment by Cybasaint** [comment]
pip install requests
