### ISSUE TITLE
Can't download course

### ISSUE THREAD

**Issue by Cjbeconfused** [calvinhobbes23/Skillshare-DL#44]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 2, in <module>
    from skillshare import Skillshare, splash
  File "/root/.Skillshare-DL/skillshare.py", line 1, in <module>
    import requests, json, sys, re, os
ModuleNotFoundError: No module named 'requests'

Is the only thing that appears

**Comment by Roselove109** [comment]
Same here,
"Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 2, in <module>
    from skillshare import Skillshare, splash
  File "/root/.Skillshare-DL/skillshare.py", line 1, in <module>
    import requests, json, sys, re, os
ModuleNotFoundError: No module named 'requests'"
