### ISSUE TITLE
List indices error

### ISSUE THREAD

**Issue by Steveeeo** [calvinhobbes23/Skillshare-DL#5]
Hi Calvin,
I want to THANK YOU for your wonderful work on this fork!
It has been working flawlessly for me until this morning, it began giving me this error:
"Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 67, in download_course_by_class_id
    for s in u['_embedded']['sessions']['_embedded']['sessions']:
TypeError: list indices must be integers or slices, not str"
hopefully, you would have some time to look at it, again thank you for help, much appreciated indeed.
Steve
![For Calvin](https://user-images.githubusercontent.com/47402162/117712507-6effac80-b1a2-11eb-9182-734163488442.png)

**Comment by Steveeeo** [comment]
I was using a old chrome portable version with this error, I thought to change browsers using a new installed version of waterfox and it worked!  Which means this error is induced by the browser, I am glad I gave it a try :).
